// All ISO 3166 countries (common names) + search aliases. Mirrors agents/jobfinder/sources/countries.py.

const countryNames = <String, String>{
  'af': 'Afghanistan',
  'al': 'Albania',
  'dz': 'Algeria',
  'as': 'American Samoa',
  'ad': 'Andorra',
  'ao': 'Angola',
  'ai': 'Anguilla',
  'aq': 'Antarctica',
  'ag': 'Antigua and Barbuda',
  'ar': 'Argentina',
  'am': 'Armenia',
  'aw': 'Aruba',
  'au': 'Australia',
  'at': 'Austria',
  'az': 'Azerbaijan',
  'bs': 'Bahamas',
  'bh': 'Bahrain',
  'bd': 'Bangladesh',
  'bb': 'Barbados',
  'by': 'Belarus',
  'be': 'Belgium',
  'bz': 'Belize',
  'bj': 'Benin',
  'bm': 'Bermuda',
  'bt': 'Bhutan',
  'bo': 'Bolivia',
  'bq': 'Bonaire, Sint Eustatius and Saba',
  'ba': 'Bosnia and Herzegovina',
  'bw': 'Botswana',
  'bv': 'Bouvet Island',
  'br': 'Brazil',
  'io': 'British Indian Ocean Territory',
  'bn': 'Brunei',
  'bg': 'Bulgaria',
  'bf': 'Burkina Faso',
  'bi': 'Burundi',
  'cv': 'Cabo Verde',
  'kh': 'Cambodia',
  'cm': 'Cameroon',
  'ca': 'Canada',
  'ky': 'Cayman Islands',
  'cf': 'Central African Republic',
  'td': 'Chad',
  'cl': 'Chile',
  'cn': 'China',
  'cx': 'Christmas Island',
  'cc': 'Cocos (Keeling) Islands',
  'co': 'Colombia',
  'km': 'Comoros',
  'cg': 'Congo',
  'ck': 'Cook Islands',
  'cr': 'Costa Rica',
  'hr': 'Croatia',
  'cu': 'Cuba',
  'cw': 'Curaçao',
  'cy': 'Cyprus',
  'cz': 'Czechia',
  'ci': 'Côte d\'Ivoire',
  'cd': 'DR Congo',
  'dk': 'Denmark',
  'dj': 'Djibouti',
  'dm': 'Dominica',
  'do': 'Dominican Republic',
  'ec': 'Ecuador',
  'eg': 'Egypt',
  'sv': 'El Salvador',
  'gq': 'Equatorial Guinea',
  'er': 'Eritrea',
  'ee': 'Estonia',
  'sz': 'Eswatini',
  'et': 'Ethiopia',
  'fk': 'Falkland Islands (Malvinas)',
  'fo': 'Faroe Islands',
  'fj': 'Fiji',
  'fi': 'Finland',
  'fr': 'France',
  'gf': 'French Guiana',
  'pf': 'French Polynesia',
  'tf': 'French Southern Territories',
  'ga': 'Gabon',
  'gm': 'Gambia',
  'ge': 'Georgia',
  'de': 'Germany',
  'gh': 'Ghana',
  'gi': 'Gibraltar',
  'gr': 'Greece',
  'gl': 'Greenland',
  'gd': 'Grenada',
  'gp': 'Guadeloupe',
  'gu': 'Guam',
  'gt': 'Guatemala',
  'gg': 'Guernsey',
  'gn': 'Guinea',
  'gw': 'Guinea-Bissau',
  'gy': 'Guyana',
  'ht': 'Haiti',
  'hm': 'Heard Island and McDonald Islands',
  'hn': 'Honduras',
  'hk': 'Hong Kong',
  'hu': 'Hungary',
  'is': 'Iceland',
  'in': 'India',
  'id': 'Indonesia',
  'ir': 'Iran',
  'iq': 'Iraq',
  'ie': 'Ireland',
  'im': 'Isle of Man',
  'il': 'Israel',
  'it': 'Italy',
  'jm': 'Jamaica',
  'jp': 'Japan',
  'je': 'Jersey',
  'jo': 'Jordan',
  'kz': 'Kazakhstan',
  'ke': 'Kenya',
  'ki': 'Kiribati',
  'kw': 'Kuwait',
  'kg': 'Kyrgyzstan',
  'la': 'Laos',
  'lv': 'Latvia',
  'lb': 'Lebanon',
  'ls': 'Lesotho',
  'lr': 'Liberia',
  'ly': 'Libya',
  'li': 'Liechtenstein',
  'lt': 'Lithuania',
  'lu': 'Luxembourg',
  'mo': 'Macao',
  'mg': 'Madagascar',
  'mw': 'Malawi',
  'my': 'Malaysia',
  'mv': 'Maldives',
  'ml': 'Mali',
  'mt': 'Malta',
  'mh': 'Marshall Islands',
  'mq': 'Martinique',
  'mr': 'Mauritania',
  'mu': 'Mauritius',
  'yt': 'Mayotte',
  'mx': 'Mexico',
  'fm': 'Micronesia',
  'md': 'Moldova',
  'mc': 'Monaco',
  'mn': 'Mongolia',
  'me': 'Montenegro',
  'ms': 'Montserrat',
  'ma': 'Morocco',
  'mz': 'Mozambique',
  'mm': 'Myanmar',
  'na': 'Namibia',
  'nr': 'Nauru',
  'np': 'Nepal',
  'nl': 'Netherlands',
  'nc': 'New Caledonia',
  'nz': 'New Zealand',
  'ni': 'Nicaragua',
  'ne': 'Niger',
  'ng': 'Nigeria',
  'nu': 'Niue',
  'nf': 'Norfolk Island',
  'kp': 'North Korea',
  'mk': 'North Macedonia',
  'mp': 'Northern Mariana Islands',
  'no': 'Norway',
  'om': 'Oman',
  'pk': 'Pakistan',
  'pw': 'Palau',
  'ps': 'Palestine',
  'pa': 'Panama',
  'pg': 'Papua New Guinea',
  'py': 'Paraguay',
  'pe': 'Peru',
  'ph': 'Philippines',
  'pn': 'Pitcairn',
  'pl': 'Poland',
  'pt': 'Portugal',
  'pr': 'Puerto Rico',
  'qa': 'Qatar',
  'ro': 'Romania',
  'ru': 'Russia',
  'rw': 'Rwanda',
  're': 'Réunion',
  'bl': 'Saint Barthélemy',
  'sh': 'Saint Helena, Ascension and Tristan da Cunha',
  'kn': 'Saint Kitts and Nevis',
  'lc': 'Saint Lucia',
  'mf': 'Saint Martin (French part)',
  'pm': 'Saint Pierre and Miquelon',
  'vc': 'Saint Vincent and the Grenadines',
  'ws': 'Samoa',
  'sm': 'San Marino',
  'st': 'Sao Tome and Principe',
  'sa': 'Saudi Arabia',
  'sn': 'Senegal',
  'rs': 'Serbia',
  'sc': 'Seychelles',
  'sl': 'Sierra Leone',
  'sg': 'Singapore',
  'sx': 'Sint Maarten (Dutch part)',
  'sk': 'Slovakia',
  'si': 'Slovenia',
  'sb': 'Solomon Islands',
  'so': 'Somalia',
  'za': 'South Africa',
  'gs': 'South Georgia and the South Sandwich Islands',
  'kr': 'South Korea',
  'ss': 'South Sudan',
  'es': 'Spain',
  'lk': 'Sri Lanka',
  'sd': 'Sudan',
  'sr': 'Suriname',
  'sj': 'Svalbard and Jan Mayen',
  'se': 'Sweden',
  'ch': 'Switzerland',
  'sy': 'Syria',
  'tw': 'Taiwan',
  'tj': 'Tajikistan',
  'tz': 'Tanzania',
  'th': 'Thailand',
  'tl': 'Timor-Leste',
  'tg': 'Togo',
  'tk': 'Tokelau',
  'to': 'Tonga',
  'tt': 'Trinidad and Tobago',
  'tn': 'Tunisia',
  'tm': 'Turkmenistan',
  'tc': 'Turks and Caicos Islands',
  'tv': 'Tuvalu',
  'tr': 'Türkiye',
  'ug': 'Uganda',
  'ua': 'Ukraine',
  'ae': 'United Arab Emirates',
  'gb': 'United Kingdom',
  'us': 'United States',
  'um': 'United States Minor Outlying Islands',
  'uy': 'Uruguay',
  'uz': 'Uzbekistan',
  'vu': 'Vanuatu',
  'va': 'Vatican City',
  've': 'Venezuela',
  'vn': 'Vietnam',
  'vg': 'Virgin Islands, British',
  'vi': 'Virgin Islands, U.S.',
  'wf': 'Wallis and Futuna',
  'eh': 'Western Sahara',
  'ye': 'Yemen',
  'zm': 'Zambia',
  'zw': 'Zimbabwe',
  'ax': 'Åland Islands',
};

/// Extra words that find a country in search ("uk" → United Kingdom, "dubai" → UAE).
const countryAliases = <String, List<String>>{
  'us': ['usa', 'u.s.', 'u.s.a.', 'united states of america', 'america', 'alabama', 'alaska', 'arizona', 'arkansas', 'california', 'colorado', 'connecticut', 'delaware', 'florida', 'hawaii', 'idaho', 'illinois', 'indiana', 'iowa', 'kansas', 'kentucky', 'louisiana', 'maine', 'maryland', 'massachusetts', 'michigan', 'minnesota', 'mississippi', 'missouri', 'montana', 'nebraska', 'nevada', 'new hampshire', 'new jersey', 'new mexico', 'new york', 'north carolina', 'north dakota', 'ohio', 'oklahoma', 'oregon', 'pennsylvania', 'rhode island', 'south carolina', 'south dakota', 'tennessee', 'texas', 'utah', 'vermont', 'virginia', 'washington', 'west virginia', 'wisconsin', 'wyoming', 'district of columbia', 'san francisco', 'seattle', 'austin', 'boston', 'chicago', 'los angeles', 'denver', 'atlanta', 'miami', 'nyc'],
  'gb': ['uk', 'u.k.', 'great britain', 'britain', 'england', 'scotland', 'wales', 'northern ireland', 'london', 'manchester', 'edinburgh', 'birmingham', 'bristol', 'cambridge', 'oxford', 'leeds', 'glasgow'],
  'ae': ['uae', 'emirates', 'dubai', 'abu dhabi', 'sharjah'],
  'in': ['bengaluru', 'bangalore', 'hyderabad', 'pune', 'chennai', 'mumbai', 'delhi', 'new delhi', 'gurgaon', 'gurugram', 'noida', 'kolkata', 'ahmedabad', 'kochi', 'karnataka', 'telangana', 'maharashtra', 'tamil nadu'],
  'ca': ['toronto', 'vancouver', 'montreal', 'ottawa', 'calgary', 'ontario', 'british columbia', 'quebec', 'alberta'],
  'au': ['sydney', 'melbourne', 'brisbane', 'perth', 'new south wales', 'victoria, australia', 'queensland'],
  'de': ['deutschland', 'berlin', 'munich', 'münchen', 'hamburg', 'frankfurt', 'cologne', 'köln', 'stuttgart'],
  'nl': ['holland', 'the netherlands', 'amsterdam', 'rotterdam', 'utrecht', 'eindhoven', 'the hague'],
  'ie': ['dublin', 'cork'],
  'fr': ['paris', 'lyon'],
  'es': ['madrid', 'barcelona', 'valencia'],
  'ch': ['zurich', 'zürich', 'geneva', 'basel', 'lausanne'],
  'se': ['stockholm', 'gothenburg'],
  'pl': ['warsaw', 'krakow', 'kraków', 'wroclaw'],
  'pt': ['lisbon', 'porto'],
  'tr': ['turkey', 'istanbul', 'ankara'],
  'cz': ['czech republic', 'prague', 'brno'],
  'nz': ['auckland', 'wellington'],
  'jp': ['tokyo', 'osaka'],
  'kr': ['korea', 'seoul'],
  'sa': ['ksa', 'riyadh', 'jeddah'],
  'qa': ['doha'],
  'my': ['kuala lumpur'],
  'za': ['johannesburg', 'cape town'],
  'br': ['são paulo', 'sao paulo', 'rio de janeiro'],
  'mx': ['mexico city', 'cdmx'],
  'it': ['milan', 'milano', 'rome', 'roma'],
  'at': ['vienna', 'wien'],
  'be': ['brussels', 'antwerp'],
  'dk': ['copenhagen'],
  'no': ['oslo'],
  'fi': ['helsinki'],
  'il': ['tel aviv'],
  'eg': ['cairo'],
  'ng': ['lagos'],
  'ke': ['nairobi'],
  'ph': ['manila'],
  'id': ['jakarta'],
  'th': ['bangkok'],
  'vn': ['ho chi minh', 'hanoi'],
  'cn': ['beijing', 'shanghai', 'shenzhen'],
  'ar': ['buenos aires'],
  'co': ['bogota', 'bogotá'],
  'cl': ['santiago, chile'],
  'ru': ['russian federation', 'moscow'],
  'ro': ['bucharest'],
  'hu': ['budapest'],
  'gr': ['athens'],
  'ee': ['tallinn'],
  'lt': ['vilnius'],
  'lv': ['riga'],
  'ua': ['kyiv', 'kiev'],
  'pk': ['karachi', 'lahore', 'islamabad'],
  'bd': ['dhaka'],
  'lk': ['colombo'],
  'np': ['kathmandu'],
  'om': ['muscat'],
  'kw': ['kuwait city'],
  'bh': ['manama'],
};

/// Display name for a saved location: ISO codes show the country name, custom locations show as typed.
String locationLabel(String value) => countryNames[value] ?? value;

/// Normalise what a user picked/typed: ISO codes, country names and aliases become a lower-case code.
String normalizeLocation(String value) {
  final v = value.trim();
  final low = v.toLowerCase();
  if (countryNames.containsKey(low)) return low;
  for (final e in countryNames.entries) {
    if (e.value.toLowerCase() == low) return e.key;
  }
  for (final e in countryAliases.entries) {
    if (e.value.contains(low)) return e.key;
  }
  return v;
}
